# coding: utf-8

# flake8: noqa

"""
    Ory Hydra API

    Documentation for all of Ory Hydra's APIs. 

    The version of the OpenAPI document: v26.2.0
    Contact: hi@ory.sh
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "v26.2.0"

# Define package exports
__all__ = [
    "JwkApi",
    "MetadataApi",
    "OAuth2Api",
    "OidcApi",
    "WellknownApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AcceptDeviceUserCodeRequest",
    "AcceptOAuth2ConsentRequest",
    "AcceptOAuth2ConsentRequestSession",
    "AcceptOAuth2LoginRequest",
    "CreateJsonWebKeySet",
    "CreateVerifiableCredentialRequestBody",
    "CredentialSupportedDraft00",
    "DeviceAuthorization",
    "DeviceUserAuthRequest",
    "ErrorOAuth2",
    "GenericError",
    "GetVersion200Response",
    "HealthNotReadyStatus",
    "HealthStatus",
    "IntrospectedOAuth2Token",
    "IsReady200Response",
    "IsReady503Response",
    "JsonPatch",
    "JsonWebKey",
    "JsonWebKeySet",
    "KeysetPaginationRequestParameters",
    "KeysetPaginationResponseHeaders",
    "OAuth2Client",
    "OAuth2ClientTokenLifespans",
    "OAuth2ConsentRequest",
    "OAuth2ConsentRequestOpenIDConnectContext",
    "OAuth2ConsentSession",
    "OAuth2LoginRequest",
    "OAuth2LogoutRequest",
    "OAuth2RedirectTo",
    "OAuth2TokenExchange",
    "OidcConfiguration",
    "OidcUserInfo",
    "RFC6749ErrorJson",
    "RejectOAuth2Request",
    "TokenPagination",
    "TokenPaginationHeaders",
    "TokenPaginationRequestParameters",
    "TokenPaginationResponseHeaders",
    "TrustOAuth2JwtGrantIssuer",
    "TrustedOAuth2JwtGrantIssuer",
    "TrustedOAuth2JwtGrantJsonWebKey",
    "VerifiableCredentialPrimingResponse",
    "VerifiableCredentialProof",
    "VerifiableCredentialResponse",
    "VerifyUserCodeRequest",
    "Version",
]

# import apis into sdk package
from ory_hydra_client.api.jwk_api import JwkApi as JwkApi
from ory_hydra_client.api.metadata_api import MetadataApi as MetadataApi
from ory_hydra_client.api.o_auth2_api import OAuth2Api as OAuth2Api
from ory_hydra_client.api.oidc_api import OidcApi as OidcApi
from ory_hydra_client.api.wellknown_api import WellknownApi as WellknownApi

# import ApiClient
from ory_hydra_client.api_response import ApiResponse as ApiResponse
from ory_hydra_client.api_client import ApiClient as ApiClient
from ory_hydra_client.configuration import Configuration as Configuration
from ory_hydra_client.exceptions import OpenApiException as OpenApiException
from ory_hydra_client.exceptions import ApiTypeError as ApiTypeError
from ory_hydra_client.exceptions import ApiValueError as ApiValueError
from ory_hydra_client.exceptions import ApiKeyError as ApiKeyError
from ory_hydra_client.exceptions import ApiAttributeError as ApiAttributeError
from ory_hydra_client.exceptions import ApiException as ApiException

# import models into sdk package
from ory_hydra_client.models.accept_device_user_code_request import AcceptDeviceUserCodeRequest as AcceptDeviceUserCodeRequest
from ory_hydra_client.models.accept_o_auth2_consent_request import AcceptOAuth2ConsentRequest as AcceptOAuth2ConsentRequest
from ory_hydra_client.models.accept_o_auth2_consent_request_session import AcceptOAuth2ConsentRequestSession as AcceptOAuth2ConsentRequestSession
from ory_hydra_client.models.accept_o_auth2_login_request import AcceptOAuth2LoginRequest as AcceptOAuth2LoginRequest
from ory_hydra_client.models.create_json_web_key_set import CreateJsonWebKeySet as CreateJsonWebKeySet
from ory_hydra_client.models.create_verifiable_credential_request_body import CreateVerifiableCredentialRequestBody as CreateVerifiableCredentialRequestBody
from ory_hydra_client.models.credential_supported_draft00 import CredentialSupportedDraft00 as CredentialSupportedDraft00
from ory_hydra_client.models.device_authorization import DeviceAuthorization as DeviceAuthorization
from ory_hydra_client.models.device_user_auth_request import DeviceUserAuthRequest as DeviceUserAuthRequest
from ory_hydra_client.models.error_o_auth2 import ErrorOAuth2 as ErrorOAuth2
from ory_hydra_client.models.generic_error import GenericError as GenericError
from ory_hydra_client.models.get_version200_response import GetVersion200Response as GetVersion200Response
from ory_hydra_client.models.health_not_ready_status import HealthNotReadyStatus as HealthNotReadyStatus
from ory_hydra_client.models.health_status import HealthStatus as HealthStatus
from ory_hydra_client.models.introspected_o_auth2_token import IntrospectedOAuth2Token as IntrospectedOAuth2Token
from ory_hydra_client.models.is_ready200_response import IsReady200Response as IsReady200Response
from ory_hydra_client.models.is_ready503_response import IsReady503Response as IsReady503Response
from ory_hydra_client.models.json_patch import JsonPatch as JsonPatch
from ory_hydra_client.models.json_web_key import JsonWebKey as JsonWebKey
from ory_hydra_client.models.json_web_key_set import JsonWebKeySet as JsonWebKeySet
from ory_hydra_client.models.keyset_pagination_request_parameters import KeysetPaginationRequestParameters as KeysetPaginationRequestParameters
from ory_hydra_client.models.keyset_pagination_response_headers import KeysetPaginationResponseHeaders as KeysetPaginationResponseHeaders
from ory_hydra_client.models.o_auth2_client import OAuth2Client as OAuth2Client
from ory_hydra_client.models.o_auth2_client_token_lifespans import OAuth2ClientTokenLifespans as OAuth2ClientTokenLifespans
from ory_hydra_client.models.o_auth2_consent_request import OAuth2ConsentRequest as OAuth2ConsentRequest
from ory_hydra_client.models.o_auth2_consent_request_open_id_connect_context import OAuth2ConsentRequestOpenIDConnectContext as OAuth2ConsentRequestOpenIDConnectContext
from ory_hydra_client.models.o_auth2_consent_session import OAuth2ConsentSession as OAuth2ConsentSession
from ory_hydra_client.models.o_auth2_login_request import OAuth2LoginRequest as OAuth2LoginRequest
from ory_hydra_client.models.o_auth2_logout_request import OAuth2LogoutRequest as OAuth2LogoutRequest
from ory_hydra_client.models.o_auth2_redirect_to import OAuth2RedirectTo as OAuth2RedirectTo
from ory_hydra_client.models.o_auth2_token_exchange import OAuth2TokenExchange as OAuth2TokenExchange
from ory_hydra_client.models.oidc_configuration import OidcConfiguration as OidcConfiguration
from ory_hydra_client.models.oidc_user_info import OidcUserInfo as OidcUserInfo
from ory_hydra_client.models.rfc6749_error_json import RFC6749ErrorJson as RFC6749ErrorJson
from ory_hydra_client.models.reject_o_auth2_request import RejectOAuth2Request as RejectOAuth2Request
from ory_hydra_client.models.token_pagination import TokenPagination as TokenPagination
from ory_hydra_client.models.token_pagination_headers import TokenPaginationHeaders as TokenPaginationHeaders
from ory_hydra_client.models.token_pagination_request_parameters import TokenPaginationRequestParameters as TokenPaginationRequestParameters
from ory_hydra_client.models.token_pagination_response_headers import TokenPaginationResponseHeaders as TokenPaginationResponseHeaders
from ory_hydra_client.models.trust_o_auth2_jwt_grant_issuer import TrustOAuth2JwtGrantIssuer as TrustOAuth2JwtGrantIssuer
from ory_hydra_client.models.trusted_o_auth2_jwt_grant_issuer import TrustedOAuth2JwtGrantIssuer as TrustedOAuth2JwtGrantIssuer
from ory_hydra_client.models.trusted_o_auth2_jwt_grant_json_web_key import TrustedOAuth2JwtGrantJsonWebKey as TrustedOAuth2JwtGrantJsonWebKey
from ory_hydra_client.models.verifiable_credential_priming_response import VerifiableCredentialPrimingResponse as VerifiableCredentialPrimingResponse
from ory_hydra_client.models.verifiable_credential_proof import VerifiableCredentialProof as VerifiableCredentialProof
from ory_hydra_client.models.verifiable_credential_response import VerifiableCredentialResponse as VerifiableCredentialResponse
from ory_hydra_client.models.verify_user_code_request import VerifyUserCodeRequest as VerifyUserCodeRequest
from ory_hydra_client.models.version import Version as Version

